canonifyurls = true
contentdir = "content"
languageCode = "en-us"
layoutdir = "layouts"
publishdir = "public"
baseurl = "http://tstromberg.github.io/"
title = "data dump."
theme = "blackcase"

[Params]
github = "https://github.com/tstromberg"
twitter = "https://twitter.com/helixblue"
disqusShortname = "tstrombergio"
showRSS = true

