baseurl = "/"
languageCode = "en-us"
title = "tstromberg"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "ephemeris"
    url = "/ephemeris"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Struggle against impermanence."
    footer = "[Github](https://github.com/tstromberg) | [Twitter](https://twitter.com/helixblue) | [Email](t+ephemeris@stromberg.org)"
    custom_css = ["css/tstromberg.css"]
